package game.gameobjects;

public enum GameobjectType {
    EMPTY,
    CASTLE,ARMORY,BARRACKS,MERCENARY_POST,
    APPLE_FARM,DAIRY_FARM,HOPS_FARM,HUNTER,WHEAT_FARM,
    BAKERY,BREWERY,GRANARY,INN,MILL,
    IRON_MINE,MARKETPLACE,PITCH_RIG,STOCKPILE,STONE,WOOD,
    ARMOURERS_WORKSHOP,BLACKSMITHS_WORKSHOP,FLETHERS_WORKSHOP,POLETURNERS_WORKSHOP,TANNER_WORKSHOP,
    APOTHECARY,CATHEDRAL,CHAPEL,CHURCH,HOVEL

}
